name: food_court_weather_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  flutter_screenutil:

  # location
  geocoding: ^2.0.5
  geolocator: ^9.0.2

  # network
  dartz: 0.10.1
  http:

  # model class generator
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # state managemnt
  stacked: ^3.0.1
  stacked_services: ^0.9.8

dev_dependencies:
  build_runner: ^2.3.2
  stacked_generator: ^0.8.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/city_data.json
